MyProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myblog.urls")),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

myblog/urls.py
from django.urls import path
from . import views

app_name = 'myblog'
urlpatterns = [
	path('', views.post_list, name='post_list'),
	path('poll/',views.poll,name='poll'),
	path('new/', views.post_new, name='post_new'),
	path('poll/<int:question_id>/vote/', views.vote, name='vote'),
	path('poll/<int:question_id>/results/',views.poll_result,name='poll_result'),
	path('<int:pk>/detail/', views.post_detail, name='post_detail'),
	path('<int:pk>/edit/', views.post_edit, name='post_edit'),
	path('poll/<int:question_id>/',views.poll_detail,name='poll_detail'),
	


]

myblog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to ='myblog/img',null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text




class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

myblog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('title', 'text','image')

myblog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Post,Question,Choice
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from .forms import PostForm
from django.urls import reverse
 


# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'myblog/post_list.html', {"posts" : posts })
    
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'myblog/poll/post_detail.html', {'post': post}) 

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('myblog:post_detail', pk=post.pk)
    
    else:

        form = PostForm()
    return render(request, 'myblog/post_edit.html', {'form': form})



def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('myblog:post_detail', pk=post.pk)
            
    else:
        form = PostForm(instance=post)
    return render(request, 'myblog/post_edit.html', {'form': form})

#poll app functions    

def poll(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:6]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'myblog/poll_index.html', context)



def poll_detail(request,question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'myblog/poll_detail.html', {'question': question})
    




def poll_result(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'myblog/poll_result.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'myblog/poll_detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('myblog:poll_result', args=(question.id,)))

myblog/templates/myblog/base.html
{% load static %}
<html>
    <head>
        <title>Blog app</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/myblog.css' %}">
    </head>
    <body>
        
        <div class="page-header">
            {% if user.is_authenticated %}
            <a href="{% url 'myblog:post_new' %}" class="top-menu" ><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            <h1><a href="{% url 'myblog:post_list' %}">Blog World</a>
                <a href="{% url 'myblog:poll' %}">   Poll</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
    
</html>

myblog/templates/myblog/poll_detail.html
{% extends 'myblog/base.html'%}
	
{% block content %}
	<h1>{{ question.question_text }}</h1>

	{% if error_message %}
	<p>
		<strong>{{ error_message }}</strong>
	</p>
	{% endif %}

		<form action="{% url 'myblog:vote' question.id %}" method="post">
			{% csrf_token %}
			{% for choice in question.choice_set.all %}
			<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
			{% endfor %}
			<input type="submit" value="Vote">
		</form>

{% endblock %}

myblog/templates/myblog/poll_index.html
{% extends 'myblog/base.html'%}

{% block content %}
{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'myblog:poll_detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
	{% else %}
		<p>No poll are available.</p>
	{% endif %}

{% endblock%}

myblog/templates/myblog/poll_result.html
{% extends 'myblog/base.html' %}

{% block content %}

	<h1>{{ question.question_text }}</h1>

	<ul>
		{% for choice in question.choice_set.all %}
		<li>{{ choice.choice_text }} --> {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
		{% endfor %}
	</ul>

	<a href="{% url 'myblog:poll_result' question.id %}">Vote again?</a>
{% endblock %}

myblog/templates/myblog/post_detail.html
{% extends 'myblog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <a class="btn btn-default" href="{% url 'myblog:post_edit' post.pk %}" ><span class="glyphicon glyphicon-pencil"></span></a>
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
        {% if error_message %}
        <p> {{ error_message }}</p>
        {% endif %}
        {% if post.image %}
            <img src="{{ post.image.url}}" height="250" width="400">
        {% endif %}
        
    </div>
{% endblock %}

myblog/templates/myblog/post_edit.html
{% extends 'myblog/base.html' %}

{% block content %}
	<h2>New post</h2>
	<form method="POST" class="post-form" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">Save</button>
	</form>
{% endblock %}

myblog/templates/myblog/post_list.html
{% extends 'myblog/base.html' %}
{% block content %}
    {% for post in posts %}
    	
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h2><a href="{% url 'myblog:post_detail' post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
            {% if post.image %}
            <p><img src="{{ post.image.url}}" height="250" width="400"></p>
            {% endif %}
            
            
        </div>
        
    {% endfor %}
{% endblock %}